# Generated by Django 5.2.10 on 2026-02-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('tid', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=4096)),
                ('value', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceType', models.CharField(choices=[('gpu', 'Gpu'), ('cpu', 'Cpu')], max_length=16)),
                ('deviceId', models.IntegerField(default=0)),
                ('monitorType', models.CharField(choices=[('mclk', 'Mclk'), ('sclk', 'Sclk'), ('temp', 'Temp'), ('power', 'Power'), ('fan%', 'Fan'), ('vram%', 'Vram'), ('gpu%', 'Gpu')], max_length=16)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Op',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpuId', models.IntegerField(default=0)),
                ('queueId', models.IntegerField(default=0)),
                ('sequenceId', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CopyApi',
            fields=[
                ('api_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rocpd.api')),
                ('stream', models.CharField(max_length=18)),
                ('size', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('kind', models.IntegerField(default=0)),
                ('dst', models.CharField(max_length=18)),
                ('src', models.CharField(max_length=18)),
                ('dstDevice', models.IntegerField(default=0)),
                ('srcDevice', models.IntegerField(default=0)),
                ('sync', models.BooleanField()),
                ('pinned', models.BooleanField()),
            ],
            bases=('rocpd.api',),
        ),
        migrations.AddField(
            model_name='api',
            name='ops',
            field=models.ManyToManyField(to='rocpd.op'),
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=4096)),
            ],
            options={
                'indexes': [models.Index(fields=['string'], name='rocpd_strin_string_c7b9cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='StackFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=0)),
                ('api_ptr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.api')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string')),
            ],
        ),
        migrations.AddField(
            model_name='op',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.AddField(
            model_name='op',
            name='opType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.op')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='apiName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.AddField(
            model_name='api',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.AddField(
            model_name='api',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.CreateModel(
            name='UString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=4096)),
            ],
            options={
                'indexes': [models.Index(fields=['string'], name='rocpd_ustri_string_84d4a7_idx')],
            },
        ),
        migrations.AddField(
            model_name='api',
            name='args',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.ustring'),
        ),
        migrations.CreateModel(
            name='KernelApi',
            fields=[
                ('api_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rocpd.api')),
                ('stream', models.CharField(max_length=18)),
                ('gridX', models.IntegerField(default=0)),
                ('gridY', models.IntegerField(default=0)),
                ('gridZ', models.IntegerField(default=0)),
                ('workgroupX', models.IntegerField(default=0)),
                ('workgroupY', models.IntegerField(default=0)),
                ('workgroupZ', models.IntegerField(default=0)),
                ('groupSegmentSize', models.IntegerField(default=0)),
                ('privateSegmentSize', models.IntegerField(default=0)),
                ('kernelName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocpd.string')),
            ],
            bases=('rocpd.api',),
        ),
    ]
