# Generated by Django 2.2.4 on 2019-08-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KernelCodeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vgpr', models.IntegerField(default=0)),
                ('sgpr', models.IntegerField(default=0)),
                ('fbar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpuId', models.IntegerField(default=0)),
                ('queueId', models.IntegerField(default=0)),
                ('sequenceId', models.IntegerField(default=0)),
                ('completionSignal', models.CharField(max_length=18)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0.99', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BarrierOp',
            fields=[
                ('op_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rocpd.Op')),
                ('signalCount', models.IntegerField()),
                ('aquireFence', models.CharField(max_length=8)),
                ('releaseFence', models.CharField(max_length=8)),
            ],
            bases=('rocpd.op',),
        ),
        migrations.CreateModel(
            name='CopyOp',
            fields=[
                ('op_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rocpd.Op')),
                ('size', models.IntegerField(default=0)),
                ('src', models.IntegerField(default=0)),
                ('dst', models.IntegerField(default=0)),
                ('sync', models.BooleanField()),
                ('pinned', models.BooleanField()),
            ],
            bases=('rocpd.op',),
        ),
        migrations.AddField(
            model_name='op',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.String'),
        ),
        migrations.AddField(
            model_name='op',
            name='inputSignals',
            field=models.ManyToManyField(related_name='_op_inputSignals_+', to='rocpd.Op'),
        ),
        migrations.AddField(
            model_name='op',
            name='opType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.String'),
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('tid', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('apiName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.String')),
                ('args', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.String')),
                ('ops', models.ManyToManyField(to='rocpd.Op')),
            ],
        ),
        migrations.CreateModel(
            name='KernelOp',
            fields=[
                ('op_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rocpd.Op')),
                ('gridX', models.IntegerField(default=0)),
                ('gridY', models.IntegerField(default=0)),
                ('gridz', models.IntegerField(default=0)),
                ('workgroupX', models.IntegerField(default=0)),
                ('workgroupY', models.IntegerField(default=0)),
                ('workgroupZ', models.IntegerField(default=0)),
                ('groupSegementSize', models.IntegerField(default=0)),
                ('privateSegementSize', models.IntegerField(default=0)),
                ('kernelArgAddress', models.CharField(max_length=18)),
                ('aquireFence', models.CharField(max_length=8)),
                ('releaseFence', models.CharField(max_length=8)),
                ('codeObject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocpd.KernelCodeObject')),
                ('kernelName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocpd.String')),
            ],
            bases=('rocpd.op',),
        ),
    ]
