# Generated by Django 3.2.7 on 2022-03-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('tid', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KernelCodeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vgpr', models.IntegerField(default=0)),
                ('sgpr', models.IntegerField(default=0)),
                ('fbar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=4096)),
                ('value', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpuId', models.IntegerField(default=0)),
                ('queueId', models.IntegerField(default=0)),
                ('sequenceId', models.IntegerField(default=0)),
                ('completionSignal', models.CharField(max_length=18)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='BarrierOp',
            fields=[
                ('op_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rocpd.op')),
                ('signalCount', models.IntegerField()),
                ('aquireFence', models.CharField(max_length=8)),
                ('releaseFence', models.CharField(max_length=8)),
            ],
            bases=('rocpd.op',),
        ),
        migrations.CreateModel(
            name='CopyApi',
            fields=[
                ('api_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rocpd.api')),
                ('stream', models.CharField(max_length=18)),
                ('size', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('kind', models.IntegerField(default=0)),
                ('dst', models.CharField(max_length=18)),
                ('src', models.CharField(max_length=18)),
                ('dstDevice', models.IntegerField(default=0)),
                ('srcDevice', models.IntegerField(default=0)),
                ('sync', models.BooleanField()),
                ('pinned', models.BooleanField()),
            ],
            bases=('rocpd.api',),
        ),
        migrations.CreateModel(
            name='KernelApi',
            fields=[
                ('api_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rocpd.api')),
                ('stream', models.CharField(max_length=18)),
                ('gridX', models.IntegerField(default=0)),
                ('gridY', models.IntegerField(default=0)),
                ('gridZ', models.IntegerField(default=0)),
                ('workgroupX', models.IntegerField(default=0)),
                ('workgroupY', models.IntegerField(default=0)),
                ('workgroupZ', models.IntegerField(default=0)),
                ('groupSegmentSize', models.IntegerField(default=0)),
                ('privateSegmentSize', models.IntegerField(default=0)),
                ('kernelArgAddress', models.CharField(max_length=18)),
                ('aquireFence', models.CharField(max_length=8)),
                ('releaseFence', models.CharField(max_length=8)),
            ],
            bases=('rocpd.api',),
        ),
        migrations.AddIndex(
            model_name='string',
            index=models.Index(fields=['string'], name='rocpd_strin_string_c7b9cd_idx'),
        ),
        migrations.AddField(
            model_name='op',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.AddField(
            model_name='op',
            name='inputSignals',
            field=models.ManyToManyField(related_name='_rocpd_op_inputSignals_+', to='rocpd.Op'),
        ),
        migrations.AddField(
            model_name='op',
            name='opType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.AddField(
            model_name='api',
            name='apiName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.AddField(
            model_name='api',
            name='args',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rocpd.string'),
        ),
        migrations.AddField(
            model_name='api',
            name='ops',
            field=models.ManyToManyField(to='rocpd.Op'),
        ),
        migrations.AddField(
            model_name='kernelapi',
            name='codeObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocpd.kernelcodeobject'),
        ),
        migrations.AddField(
            model_name='kernelapi',
            name='kernelName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rocpd.string'),
        ),
    ]
