# Generated by Django 2.2.4 on 2020-06-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocpd', '0002_auto_20190813_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=4096)),
                ('value', models.CharField(max_length=4096)),
            ],
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
