# Generated by Django 3.2.7 on 2021-09-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocpd', '0003_auto_20200617_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kernelop',
            old_name='groupSegementSize',
            new_name='groupSegmentSize',
        ),
        migrations.RenameField(
            model_name='kernelop',
            old_name='privateSegementSize',
            new_name='privateSegmentSize',
        ),
    ]
