name: Bug Report
description: Something isn't working as expected.
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
    validations:
      required: true
